export const SEARCH_MOVIE = 'SEARCH_MOVIE';
export const FETCH_TMDB_MOVIES = 'FETCH_TMDB_MOVIES';
export const FETCH_TMDB_MOVIE = 'FETCH_TMDB_MOVIE';
export const IMPORT_TV_SHOW = 'IMPORT_TV_SHOW';
export const FETCH_IMPORTED_TV_SHOWS = 'FETCH_IMPORTED_TV_SHOWS';
export const LOADING = 'LOADING';
